spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:15432/postgres
    username: postgres
    password: 1234
    pool:
      max-size: 100
  application:
    name: QNA-SERVICE
  config:
    import: "optional:configserver:"
  main:
    allow-bean-definition-overriding : true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
# actuator 추가
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh, info, metrics, prometheus,env
      
